### ISSUE TITLE
original_title don't getting from imdb liberary

### ISSUE THREAD

**Issue by hiltwork** [Tony0892/Codeigniter-IMDb-Scraper-Library#2]
original_title don't getting from imdb liberary.

**Comment by svenvanhees** [comment]
This library is not maintained anymore and will not work. Please find an other library.

**Comment by hiltwork** [comment]
Can you please suggest me any other reliable library ?

**Comment by svenvanhees** [comment]
I think this library is actively maintained: https://github.com/dhobi/PHP-IMDb-Scraper
